- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(2)(bc61c3e5-a15e-4e51-9d97-450f52ec885b)'
    subscriptionId: 'bc61c3e5-a15e-4e51-9d97-450f52ec885b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'devops'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'template.json'
    deploymentMode: 'Incremental'